/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://zbtjyttqnnbtfatlnyo375sxte.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-anm2gmyiwbcyllio7ez4r3klb4",
    "aws_cognito_identity_pool_id": "ap-south-1:3a36f5b0-e288-481e-9787-5facf2757d41",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_2hte8hQQg",
    "aws_user_pools_web_client_id": "1bttsjfgl7glo3d08uidbnv8m",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "BIRTHDATE",
        "PHONE_NUMBER",
        "NAME",
        "PICTURE"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "infiction-web-app-storage143026-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
